2021/02/18 08:12:09 : customers_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3628, in customer_import
    self.insert_map(self.TYPE_CUSTOMER, convert['id'], customer_id, convert['code'])
NameError: name 'customer_id' is not defined

2021/02/18 08:12:09 : customers_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3628, in customer_import
    self.insert_map(self.TYPE_CUSTOMER, convert['id'], customer_id, convert['code'])
NameError: name 'customer_id' is not defined

