2021/02/14 19:58:29 : products_errors 9: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 10: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 16: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 17: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 18: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 19: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 20: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 22: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 23: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 24: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 25: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 37: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 39: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 41: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 42: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 43: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 44: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 47: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 48: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

2021/02/14 19:58:29 : products_errors 49: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 525, in convert_product_export
    product_data['id'] = product['id']
KeyError: 'id'

