2021/02/17 15:48:16 : orders_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 2: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 4: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 5: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 6: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 7: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/17 15:48:16 : orders_errors 8: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4013, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

