2021/02/14 20:22:53 : categories_errors 2: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    category_data['active'] = True if category['active']=='1' else False
KeyError: 'active'

2021/02/14 20:23:16 : categories_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    category_data['active'] = True if category['active']=='1' else False
KeyError: 'active'

2021/02/14 20:23:45 : categories_errors 4: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 381, in convert_category_export
    category_data['active'] = True if category['active']=='1' else False
KeyError: 'active'

