2021/02/19 13:42:27 : customers_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3691, in customer_import
    'user_registered': convert['customers_info_date_account_created'] if convert['customers_info_date_account_created'] else '',
KeyError: 'customers_info_date_account_created'

2021/02/19 13:42:27 : customers_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3691, in customer_import
    'user_registered': convert['customers_info_date_account_created'] if convert['customers_info_date_account_created'] else '',
KeyError: 'customers_info_date_account_created'

