2021/02/14 20:45:45 : categories_errors 2: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 4: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 5: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 6: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 7: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 8: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 9: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 10: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 11: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 12: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:45 : categories_errors 13: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 14: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 15: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 16: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 17: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 19: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 20: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 22: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

2021/02/14 20:45:46 : categories_errors 23: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 1414, in category_import
    response = self.api('custom_collections.json', post_data, 'Post')
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 3699, in api
    data = json.dumps(data)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

